name = "poa-ipfs"
main = "cloudflare-worker/worker.mjs"
compatibility_date = "2024-03-30"

[vars]
PINATA_GATEWAY = "https://ipfs.poa.earth"

# Attach to your zone + routes
routes = [
  { pattern = "poa.earth/*", zone_name = "poa.earth" },
  { pattern = "www.poa.earth/*", zone_name = "poa.earth" }
]
